name: ci-docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 1 * * *'

  workflow_dispatch:

env:
    REGISTRY: ghcr.io
    DOCKER_REPOSITORY: hureitdocker
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    IMAGE_NAME: webapi-hureit-netcore
    IMAGE_TAG: ${{ github.run_number }}

jobs:

  build-push-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - name: Push Image to Docker Hub
      id: build-and-push
      uses: docker/build-push-action@v2.9.0
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: cosign-installer
      if: github.event_name != 'pull_request'
      uses: sigstore/cosign-installer@d6a3abf1bdea83574e28d40543793018b6035605
      with:
          cosign-release: 'v1.7.1'

    - name: Sign the published Docker image
      if: ${{ github.event_name != 'pull_request' }}
      env:
        COSIGN_EXPERIMENTAL: "true"
      run:
        cosign sign ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}@${{ steps.build-and-push.outputs.digest }}