name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 1 * * *'

  workflow_dispatch:

env:
    REGISTRY: ghcr.io
    DOCKER_REPOSITORY: hureitdocker
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    IMAGE_NAME: webapi-hureit-netcore
    IMAGE_TAG: 0.0.${{ GITHUB_RUN_ID }}

jobs:

  build-push-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
    - uses: actions/checkout@v3

    - name: Build to Docker image
      run:
        docker build . --file Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG --build-arg=token=ZGEzNTQ5Y2QyNjAx --no-cache